# Generated by Django 6.0.3 on 2026-03-16 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='total_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
