# Generated by Django 6.0.3 on 2026-03-21 13:54

from django.db import migrations, models


def normalize_pending_status(apps, schema_editor):
    Booking = apps.get_model("booking", "Booking")
    Booking.objects.filter(status="prnding").update(status="pending")


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_status_booking_user'),
    ]

    operations = [
        migrations.RunPython(normalize_pending_status, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('canceled', 'Canceled')], default='pending', max_length=120),
        ),
    ]
